# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partes', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_ato', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('analise', 'Em Análise'), ('assinatura', 'Assinatura'), ('selagem', 'Selagem'), ('arquivado', 'Arquivado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=16)),
                ('sla_at', models.DateTimeField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'processos',
            },
        ),
        migrations.CreateModel(
            name='ProcessoParte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('outorgante', 'Outorgante'), ('outorgado', 'Outorgado'), ('testemunha', 'Testemunha'), ('interveniente', 'Interveniente'), ('outro', 'Outro')], max_length=32)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='partes.parte')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='processos.processo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'processo_partes',
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('ano', models.PositiveIntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('interno', 'Interno')], default='entrada', max_length=16)),
                ('observacoes', models.TextField(blank=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='processos.processo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'protocolos',
                'indexes': [models.Index(fields=['tenant', 'ano', 'numero'], name='ix_protocolo_tenant_ano_numero'), models.Index(fields=['tenant', 'processo'], name='ix_protocolo_tenant_processo')],
            },
        ),
        migrations.AddConstraint(
            model_name='protocolo',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero', 'ano'), name='uq_protocolo_tenant_numero_ano'),
        ),
        migrations.AddConstraint(
            model_name='processoparte',
            constraint=models.UniqueConstraint(fields=('tenant', 'processo', 'parte', 'papel'), name='uq_processo_parte_papel'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['tenant', 'status'], name='ix_proc_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['tenant', 'tipo_ato', 'status'], name='ix_proc_tenant_tipo_status'),
        ),
    ]
