# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedMinuta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_command', models.TextField(help_text='Original user command')),
                ('parsed_intent', models.JSONField(help_text='Parsed intent from AI')),
                ('ai_model_version', models.CharField(help_text='AI model version used', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0.0 to 1.0)')),
                ('generation_time_ms', models.PositiveIntegerField(help_text='Generation time in milliseconds')),
                ('clauses_used', models.JSONField(default=list, help_text='List of clause IDs used')),
                ('template_source', models.CharField(choices=[('tenant', 'Tenant'), ('lexnode', 'LexNode'), ('ai_generated', 'AI Generated')], default='ai_generated', help_text='Source of the template used', max_length=20)),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_generated_minutas',
                'ordering': ['-generation_timestamp'],
            },
        ),
    ]
