# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_documents', '0001_initial'),
        ('documentos', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedminuta',
            name='minuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='documentos.minuta'),
        ),
        migrations.AddField(
            model_name='aigeneratedminuta',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='aigeneratedminuta',
            index=models.Index(fields=['tenant', 'generation_timestamp'], name='ix_ai_generated_timestamp'),
        ),
        migrations.AddIndex(
            model_name='aigeneratedminuta',
            index=models.Index(fields=['tenant', 'template_source'], name='ix_ai_generated_source'),
        ),
        migrations.AddIndex(
            model_name='aigeneratedminuta',
            index=models.Index(fields=['confidence_score'], name='ix_ai_generated_confidence'),
        ),
    ]
