# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('diff_json', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id', 'ts'], name='ix_audit_resource'), models.Index(fields=['tenant', 'actor', 'ts'], name='ix_audit_actor')],
            },
        ),
    ]
