"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add packages directory to Python path
# In Docker, packages is mounted at /packages
# In local dev, it's at the project root
if os.path.exists('/packages'):
    sys.path.insert(0, '/packages')
elif os.path.exists(BASE_DIR.parent.parent / 'packages'):
    sys.path.insert(0, str(BASE_DIR.parent.parent / 'packages'))

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mrab6g)j5xqsd#jr$+_rs_gi$guk+gwny8na+loe5has!#@&%9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'notarius-api'])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "corsheaders",
    "apps.authentication",
    "apps.auditoria",
    "apps.base",
    "apps.tenancy",
    "apps.profiles",
    "apps.documentos",
    "apps.templates",
    "apps.ai_documents",
    "apps.analytics",
    "apps.workflows",
    "apps.partes",
    "apps.processos",
    "apps.validation",
    "apps.fees",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.tenancy.middlewares.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Always use PostgreSQL via DATABASE_URL in Docker/production
# For local development without Docker, SQLite can be used but DATABASE_URL should be set
DATABASE_URL = env.str('DATABASE_URL', default='')
if DATABASE_URL:
    # Use PostgreSQL from DATABASE_URL
    DATABASES = {
        'default': env.db('DATABASE_URL', default=DATABASE_URL)
    }
else:
    # Fallback to SQLite only for local development (not in Docker)
    # In Docker, DATABASE_URL should always be set
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads, PDFs, etc.)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Jinja2 configuration
JINJA2_TEMPLATES_DIR = BASE_DIR / "templates" / "documentos"

# PDF Generation
PDF_TEMP_DIR = BASE_DIR / "media" / "pdfs"
PDF_FONTS_DIR = BASE_DIR / "fonts"

# Storage configuration - Use MinIO by default in development
USE_S3 = env.bool('USE_S3', default=True)
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID', default='minioadmin')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY', default='minioadmin')
AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME', default='notarius-files')
AWS_S3_ENDPOINT_URL = env.str('AWS_S3_ENDPOINT_URL', default='http://localhost:9000')  # MinIO service for URLs
AWS_S3_INTERNAL_ENDPOINT_URL = env.str('AWS_S3_INTERNAL_ENDPOINT_URL', default='http://localhost:9000')  # MinIO internal service
AWS_S3_REGION_NAME = env.str('AWS_S3_REGION_NAME', default='us-east-1')

# Configure MinIO for static and media files
# Note: During Docker build, USE_S3 will be False to allow collectstatic to work
# At runtime, USE_S3 will be True and files will be served from MinIO
if USE_S3:
    # Static files served from MinIO
    STATICFILES_STORAGE = 'apps.base.storage.MinIOStaticStorage'
    # In development, serve static files through Django to avoid CORS/browser issues
    # In production, files can be served directly from MinIO
    if DEBUG:
        STATIC_URL = "/static/"
    else:
        STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/"
    
    # Media files served from MinIO
    DEFAULT_FILE_STORAGE = 'apps.base.storage.MinIOMediaStorage'
    # In development, serve media files through Django
    if DEBUG:
        MEDIA_URL = "/media/"
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
    
    # S3 storage settings
    AWS_S3_CUSTOM_DOMAIN = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_FILE_OVERWRITE = False

# Signature
SIGNATURE_DEADLINE_DAYS = 30  # default deadline for signatures
MOCK_SIGNATURE_ENABLED = DEBUG  # only allow mock in dev

# Workflow Orchestrator Feature Flags
ENABLE_ENOTARIADO = env.bool('ENABLE_ENOTARIADO', default=True)
ENABLE_RI_CENTRAL = env.bool('ENABLE_RI_CENTRAL', default=True)
ENABLE_RTDPJ_CENTRAL = env.bool('ENABLE_RTDPJ_CENTRAL', default=True)
ENABLE_PROTESTO_CENTRAL = env.bool('ENABLE_PROTESTO_CENTRAL', default=True)

# AI Configuration
AI_MODEL_VERSION = env.str('AI_MODEL_VERSION', default='gpt-4o-mini')
OPENAI_API_KEY = env.str('OPENAI_API_KEY', default='')
AI_GENERATION_ENABLED = env.bool('AI_GENERATION_ENABLED', default=True)
AI_CONFIDENCE_THRESHOLD = env.float('AI_CONFIDENCE_THRESHOLD', default=0.7)

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001", 
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-id',
]
