# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500)),
                ('hash_sha256', models.BinaryField()),
                ('mime', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('erro', 'Erro')], default='novo', max_length=20)),
            ],
            options={
                'db_table': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corpo_md', models.TextField(help_text='Markdown content of the minuta')),
                ('variaveis_json', models.JSONField(default=dict, help_text='PII variables as tokens')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('gerada_por', models.CharField(choices=[('usuario', 'Usuário'), ('ai', 'IA')], default='usuario', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('citations', models.JSONField(default=list, help_text='Legal citations used in generation')),
                ('grounding_confidence', models.FloatField(help_text='Confidence score for legal grounding', null=True)),
                ('skeleton_cache_key', models.CharField(blank=True, db_index=True, help_text='Cache key for document skeleton', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_minutas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'minutas',
                'ordering': ['-created_at'],
            },
        ),
    ]
