# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'procuracao', 'certidao')", max_length=100)),
                ('document_type', models.CharField(help_text='Type of document (procuracao, certidao, testamento, etc.)', max_length=50)),
                ('template_path', models.CharField(help_text='Path to template file', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Is this a default template?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('version', models.CharField(default='1.0', help_text='Template version', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this template')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript for this template')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom fields for this template')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_templates',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('document_type', models.CharField(help_text='Type of document', max_length=50)),
                ('corpo_template', models.TextField(help_text='Template content with Jinja2 syntax')),
                ('schema', models.JSONField(default=dict, help_text='Template variable schema')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('version', models.CharField(default='1.0', help_text='Template version', max_length=20)),
                ('source', models.CharField(choices=[('tenant', 'Tenant'), ('lexnode', 'LexNode'), ('ai_generated', 'AI Generated')], default='tenant', help_text='Source of this template', max_length=20)),
                ('jurisdiction', models.CharField(blank=True, help_text='Legal jurisdiction (for lexnode templates)', max_length=10)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('quality_score', models.FloatField(blank=True, help_text='User feedback quality score (0.0 to 1.0)', null=True)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_content_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'templates',
                'indexes': [models.Index(fields=['tenant', 'document_type'], name='ix_template_content_type'), models.Index(fields=['tenant', 'is_active'], name='ix_template_content_active'), models.Index(fields=['tenant', 'source'], name='ix_template_content_source'), models.Index(fields=['tenant', 'jurisdiction'], name='ix_template_jurisdiction'), models.Index(fields=['usage_count'], name='ix_template_content_usage')],
            },
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_template_content_name'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['tenant', 'document_type'], name='ix_template_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['tenant', 'is_default'], name='ix_template_tenant_default'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='ix_template_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_template_tenant_name'),
        ),
    ]
