# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], help_text='pf or pj', max_length=2, null=True)),
                ('nome_token', models.CharField(blank=True, help_text='PII Vault token for name', max_length=255, null=True)),
                ('nome_hash', models.BinaryField(blank=True, db_index=True, help_text='SHA256 hash for deduplication', null=True)),
                ('cpf_token', models.CharField(blank=True, help_text='PII Vault token for CPF', max_length=255, null=True)),
                ('cpf_hash', models.BinaryField(blank=True, db_index=True, help_text='SHA256 hash for CPF', null=True)),
                ('cnpj_token', models.CharField(blank=True, help_text='PII Vault token for CNPJ', max_length=255, null=True)),
                ('cnpj_hash', models.BinaryField(blank=True, db_index=True, help_text='SHA256 hash for CNPJ', null=True)),
                ('endereco_token', models.CharField(blank=True, help_text='PII Vault token for address', max_length=255, null=True)),
                ('telefone_token', models.CharField(blank=True, help_text='PII Vault token for phone', max_length=255, null=True)),
                ('email_token', models.CharField(blank=True, help_text='PII Vault token for email', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-sensitive data only')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_partes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_partes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partes',
                'indexes': [models.Index(fields=['tenant', 'nome_hash'], name='ix_parte_tenant_nome_hash'), models.Index(fields=['tenant', 'cpf_hash'], name='ix_parte_tenant_cpf_hash'), models.Index(fields=['tenant', 'cnpj_hash'], name='ix_parte_tenant_cnpj_hash'), models.Index(fields=['tenant', 'tipo_pessoa'], name='ix_parte_tenant_tipo')],
            },
        ),
    ]
