# Generated by Django 4.2.26 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0002_initial'),
        ('processos', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Template name', max_length=100)),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], help_text='Notification type', max_length=20)),
                ('trigger', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('deadline_approaching', 'Deadline Approaching'), ('document_ready', 'Document Ready'), ('signature_required', 'Signature Required'), ('custom', 'Custom')], help_text='Trigger event', max_length=30)),
                ('assunto', models.CharField(help_text='Subject line', max_length=200)),
                ('corpo', models.TextField(help_text='Message body')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('variables', models.JSONField(default=list, help_text='Available template variables')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=200)),
                ('recipient_email', models.EmailField(help_text='Recipient email', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, help_text='Recipient phone', max_length=20)),
                ('rendered_subject', models.CharField(help_text='Rendered subject', max_length=200)),
                ('rendered_body', models.TextField(help_text='Rendered message body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('context_data', models.JSONField(default=dict, help_text='Context data used for rendering')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workflows.notificationtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoNota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Note title', max_length=200)),
                ('conteudo', models.TextField(help_text='Note content')),
                ('is_private', models.BooleanField(default=False, help_text='Is this a private note?')),
                ('is_resolved', models.BooleanField(default=False, help_text='Is this note resolved?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documento_notas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='documentos.documento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'documento_notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Task title', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Task description')),
                ('tipo', models.CharField(choices=[('autenticacao', 'Autenticação'), ('assinatura', 'Assinatura'), ('revisao', 'Revisão'), ('aprovacao', 'Aprovação'), ('finalizacao', 'Finalização'), ('outro', 'Outro')], help_text='Task type', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendente', max_length=15)),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional task metadata')),
                ('notes', models.TextField(blank=True, help_text='Task notes and comments')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='documentos.documento')),
                ('minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='documentos.minuta')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='processos.processo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'workflow_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ix_workflow_task_status'), models.Index(fields=['tenant', 'tipo'], name='ix_workflow_task_tipo'), models.Index(fields=['tenant', 'assigned_to'], name='ix_workflow_task_assigned'), models.Index(fields=['deadline'], name='ix_workflow_task_deadline')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'tipo'], name='ix_notification_template_tipo'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'trigger'], name='ix_notification_trigger'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='ix_notification_active'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'status'], name='ix_notification_log_status'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'recipient_email'], name='ix_notification_log_email'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'sent_at'], name='ix_notification_log_sent'),
        ),
        migrations.AddIndex(
            model_name='documentonota',
            index=models.Index(fields=['tenant', 'documento'], name='ix_documento_nota_doc'),
        ),
        migrations.AddIndex(
            model_name='documentonota',
            index=models.Index(fields=['tenant', 'is_private'], name='ix_documento_nota_private'),
        ),
        migrations.AddIndex(
            model_name='documentonota',
            index=models.Index(fields=['tenant', 'is_resolved'], name='ix_documento_nota_resolved'),
        ),
    ]
