# Generated by Django 4.2.26 on 2025-11-05 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRELLISClusterMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=255, unique=True)),
                ('cluster_name', models.CharField(max_length=255)),
                ('total_interactions', models.IntegerField(default=0)),
                ('interactions_last_7_days', models.IntegerField(default=0)),
                ('interactions_last_30_days', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0.0)),
                ('negative_sentiment_count', models.IntegerField(default=0)),
                ('positive_sentiment_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('user_acceptance_rate', models.FloatField(default=0.0)),
                ('user_edit_rate', models.FloatField(default=0.0)),
                ('avg_processing_time_ms', models.IntegerField(default=0)),
                ('strategic_priority', models.IntegerField(default=1)),
                ('revenue_impact', models.CharField(default='medium', max_length=50)),
                ('priority_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_refinement', models.BooleanField(default=False)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'trellis_cluster_metrics',
            },
        ),
        migrations.CreateModel(
            name='TRELLISInteractionLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('original_command', models.TextField()),
                ('parsed_intent', models.JSONField()),
                ('matched_cluster', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_confidence', models.FloatField(default=0.0)),
                ('used_deterministic_parser', models.BooleanField(default=False)),
                ('used_llm_fallback', models.BooleanField(default=False)),
                ('user_accepted', models.BooleanField(blank=True, null=True)),
                ('user_edited', models.BooleanField(default=False)),
                ('user_regenerated', models.BooleanField(default=False)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('user_feedback_text', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField()),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('llm_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('success', models.BooleanField()),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trellis_interaction_log',
                'indexes': [models.Index(fields=['matched_cluster', 'created_at'], name='trellis_int_matched_6502cf_idx'), models.Index(fields=['user', 'session_id'], name='trellis_int_user_id_8fc8a4_idx'), models.Index(fields=['success', 'created_at'], name='trellis_int_success_647d21_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of usage')),
                ('total_generations', models.PositiveIntegerField(default=0)),
                ('successful_generations', models.PositiveIntegerField(default=0)),
                ('failed_generations', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_generation_time_ms', models.PositiveIntegerField(default=0)),
                ('most_used_templates', models.JSONField(default=list)),
                ('most_used_clauses', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ai_usage_analytics',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
