# Generated by Django 4.2.26 on 2025-11-05 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('nome', 'uf'), name='uq_tenant_nome_uf'),
        ),
    ]
