# Generated by Django 4.2.26 on 2025-11-05 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registry_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['nome', 'uf'], name='ix_tenant_nome_uf'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['municipio'], name='ix_tenant_municipio'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['uf'], name='ix_tenant_uf'),
        ),
    ]
